<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEvents()
    {
        $query = $this->createQueryBuilder('e')
            ->orderBy('e.dateStart', 'DESC')
            ->getQuery();

        return $query->getResult();
    }

    public function findWithJoins($id)
    {
        $query = $this->createQueryBuilder('e')
            ->addSelect('et, pl, p')
            ->leftJoin('e.eventType', 'et')
            ->leftJoin('e.place', 'pl')
            ->leftJoin('e.posts', 'p')
            ->where('e.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
